# ./buildspec.yml
version: 0.2

env:
  variables:
    GIT_URL_INSTEAD_OF: "https://github.com/=git@github.com:"

phases:
  install:
    commands:
      - wget https://github.com/earthly/earthly/releases/latest/download/earth-linux-amd64 -O /usr/local/bin/earth && chmod +x /usr/local/bin/earth
  build:
    commands:
      - echo Logging in $DOCKERHUB_USERNAME
      - docker login --username "$DOCKERHUB_USERNAME" --password "$DOCKERHUB_TOKEN"
      - earth --version
      - earth --push +build